apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-template
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fastapi.example.com
      secretName: fastapi-template-tls
  rules:
    - host: fastapi.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-template
                port:
                  number: 80
