apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fastapi-template
spec:
  podSelector:
    matchLabels:
      app: fastapi-template
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: 8000
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: fastapi-postgres
        - podSelector:
            matchLabels:
              app: fastapi-redis
      ports:
        - port: 5432
        - port: 6379
    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
