"""add task status table

Revision ID: <auto-generated>
Revises: 9d1a1b0c1d2e
Create Date: <auto-generated>

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "003_task_status"
down_revision: str | None = "9d1a1b0c1d2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "task_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(255), nullable=False),
        sa.Column("name", sa.String(255), nullable=True),
        sa.Column("status", sa.String(50), nullable=False, server_default="PENDING"),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_index(op.f("ix_task_status_task_id"), "task_status", ["task_id"], unique=True)


def downgrade() -> None:
    op.drop_index(op.f("ix_task_status_task_id"), table_name="task_status")
    op.drop_table("task_status")
