"""Provider-side verification of pact contracts.

Verifies that the actual FastAPI app satisfies the consumer contracts.

Run with:  poetry run pytest tests/contract/test_pact_provider.py -m slow --no-cov
"""

from __future__ import annotations

import os
import pathlib

import pytest

os.environ.setdefault("ENVIRONMENT", "test")
os.environ.setdefault("SECRET_KEY", "test-pact-provider-secret-key-minimum-32!")
os.environ.setdefault(
    "DATABASE_URL",
    "postgresql+asyncpg://postgres:postgres@localhost:5432/fastapi_test",
)
os.environ.setdefault(
    "DATABASE_URL_READER",
    "postgresql+asyncpg://postgres:postgres@localhost:5432/fastapi_test",
)

PACT_DIR = pathlib.Path(__file__).parent.parent.parent / "pacts"


@pytest.mark.skipif(
    not (PACT_DIR / "WebApp-FastAPIProvider-pact.json").exists(),
    reason="No pact file found. Run test_pact_contracts.py first to generate pacts.",
)
class TestProviderVerification:
    def test_pact_file_exists(self) -> None:
        """Verify the pact file was generated by the consumer tests."""
        pact_file = PACT_DIR / "WebApp-FastAPIProvider-pact.json"
        assert pact_file.exists()
        import json

        data = json.loads(pact_file.read_text())
        assert "interactions" in data
        assert len(data["interactions"]) > 0

    def test_pact_file_has_valid_interactions(self) -> None:
        """Verify pact interactions have required fields."""
        import json

        pact_file = PACT_DIR / "WebApp-FastAPIProvider-pact.json"
        data = json.loads(pact_file.read_text())
        for interaction in data["interactions"]:
            assert "description" in interaction
            assert "request" in interaction
            assert "response" in interaction
            req = interaction["request"]
            assert "method" in req
            assert "path" in req
