apiVersion: v2
name: async-fastapi-template
description: A Helm chart for the FastAPI template
type: application
version: 0.3.0
appVersion: "3.1.0"

dependencies:
  - name: flagger
    version: "1.36.1"
    repository: "https://flagger.app"
    condition: canary.enabled
